### PR TITLE
Revert "Use become instead of sudo"

### PR DESCRIPTION
**Pull request by dasJ**
Reverts stuvusIT/slapd-base#11

### CODE REVIEW

**Comment by SlothOfAnarchy** [comment]
Why?
To me it looks just like you didn't test your changes before.

**Comment by dasJ** [comment]
@SlothOfAnarchy I didn't

**Comment by SlothOfAnarchy** [comment]
@dasJ So tell me, what is the problem? I think using `become_user` would be way cleaner!

**Comment by dasJ** [comment]
No, it doesn't work like that. Ansible puts the temporary python module on the server as root, and then `sudo`s to an unprivileged user which (of course) can't read the script. 

That's one of Ansible's sources of suck.

**Comment by SlothOfAnarchy** [comment]
Okay. I think @Scriptkiddi also ran into this problem.

**Review by SlothOfAnarchy — APPROVED** [review]

**Pull request merged**
